version: '3'
services:
  terrabender:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    environment:
     - CONFIG_WEBSERVER_ENABLED=true
     - CONFIG_PLAN_ENABLED=true
     - CONFIG_APPLY_ENABLED=true
     - CONFIG_REBASE_ENABLED=true
     - CONFIG_REBASE_REQUIRED=false
     - CONFIG_MERGE_ENABLED=true
     - CONFIG_GIT_PROVIDER=github
     - CONFIG_DAEMON_ENABLED=true
     - CONFIG_GIT_API_KEY
